apiVersion: v1
data:
  config.json: |
    {
                "data_directory": "./data",
                "listeners": {
                        "udp_port": 41234,
                        "tcp_port": 7070
                },
                "logger": {
                        "level": "info",
                        "path": "/tmp/",
                        "max_size": 134217728
                },
                "dbManager": {
                        "file": "metrics.db",
                        "retentionInSeconds": 3600,
                        "housekeepingIntervalInSeconds": 60,
                        "enabled": false
                },
                "connector": {
                        "mqtt": {
                                "host": {pdt_hostname},
                                "port": {pdt_mqtt_port},
                                "websockets": false,
                                "qos": 1,
                                "retain": false,
                                "secure": true,
                                "retries": 5,
                                "strictSSL": false,
                                "sparkplugB": true,
                                "version": "spBv1.0"   
                        }
                }
        }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {pod_name}-global-devices-config
